import type { MediaFile } from '@/types/mediaFile';
import type { Service } from '@/types/service';

const MEDIA_URL = import.meta.env.MEDIA_URL;

const addCarouselImages = (services: Service[]) => {
  return services.map((service) => {
    return {
      ...service,
      image: {
        ...service.image,
        url: `${MEDIA_URL}/services/${service.slug}/${service.image.alt}`,
      } as MediaFile,
      allMediaFiles: service.allMediaFiles.map((mediaFile) => {
        return {
          ...mediaFile,
          url:
            mediaFile.type === 'video'
              ? mediaFile.url
              : `${MEDIA_URL}/services/${service.slug}/${mediaFile.alt}`,
        };
      }) as MediaFile[],
      carouselMediaFiles: service.carouselMediaFiles.map((mediaFile) => {
        return {
          ...mediaFile,
          url:
            mediaFile.type === 'video'
              ? mediaFile.url
              : `${MEDIA_URL}/services/${service.slug}/${mediaFile.alt}`,
        };
      }) as MediaFile[],
    };
  });
};

export const SERVICES: Service[] = addCarouselImages([
  {
    slug: 'fotos-bodas',
    name: 'Fotografía de Bodas',
    description:
      'Capturamos cada emoción de tu boda con un estilo natural, elegante y atemporal. Nuestro servicio de fotografía de bodas inmortaliza los momentos más importantes de tu gran día para que puedas revivirlos por siempre.',
    portfolioDescription:
      'Tu historia de amor contada en imágenes reales, emotivas y llenas de vida.',
    points: [
      {
        title: 'Momentos reales, sin poses forzadas',
        description:
          'Capturamos cada risa, lágrima y abrazo de forma natural, para que tus fotos reflejen exactamente lo que viviste.',
      },
      {
        title: 'Cobertura completa de tu gran día',
        description:
          'Desde los preparativos hasta la fiesta, documentamos cada etapa de tu boda con un enfoque artístico y profesional.',
      },
      {
        title: 'Recuerdos que duran para siempre',
        description:
          'Entregamos fotografías de alta calidad, ideales para álbumes, redes sociales e impresiones de gran formato.',
      },
    ],
    seoDescription:
      'Fotografía de bodas en Lima con estilo natural y elegante. Cobertura completa de tu gran día, desde los preparativos hasta la fiesta. Cotiza con Visual Studio.',
    about: [
      'El día de tu boda pasa en un instante, pero las fotografías se quedan para siempre. Nuestro servicio de fotografía de bodas en Lima está pensado para que puedas revivir cada emoción tal como la sentiste: la risa nerviosa antes de entrar, la mirada del reencuentro en el altar, el abrazo de tu familia y la energía de la fiesta. Trabajamos con un estilo natural, elegante y atemporal, sin poses forzadas ni momentos artificiales.',
      'Documentamos tu boda de principio a fin. Empezamos con los preparativos de los novios, seguimos con la ceremonia, la sesión de pareja y la recepción, cuidando tanto los grandes momentos como los detalles que hacen única tu celebración. Nuestro enfoque combina el reportaje documental (capturar lo que sucede de forma espontánea) con retratos cuidados que resaltan la conexión entre ustedes y con sus seres queridos.',
      'Cada boda se entrega con edición profesional y en alta calidad, lista para tu álbum, tus redes sociales o impresiones de gran formato. Si te casas en Lima o en provincia, conversamos tu historia, la locación y el estilo que buscas para armar una cobertura a la medida. Reserva tu fecha con anticipación: las mejores fechas se agendan con meses de anticipación.',
    ],
    faqs: [
      {
        question: '¿Cuánto cuesta un servicio de fotografía de bodas en Lima?',
        answer:
          'El precio depende de las horas de cobertura, la cantidad de fotógrafos, si incluye sesión previa y el tipo de entrega (digital, álbum, impresiones). Armamos paquetes según el tamaño y el estilo de tu boda. Escríbenos por WhatsApp con tu fecha y te enviamos una cotización sin compromiso.',
      },
      {
        question: '¿La cobertura incluye los preparativos y la fiesta?',
        answer:
          'Sí. Nuestra cobertura completa documenta todo el día: los preparativos de los novios, la ceremonia, la sesión de pareja y la recepción. En la cotización definimos las horas de cobertura que necesitas según el programa de tu boda.',
      },
      {
        question: '¿Con cuánta anticipación debo reservar la fecha?',
        answer:
          'Recomendamos reservar con varios meses de anticipación, sobre todo para fechas de temporada alta (fines de semana y meses de mayor demanda). Apenas tengas la fecha confirmada, escríbenos para asegurar tu día en nuestra agenda.',
      },
    ],
    videos: ['BRiH4IwjqbA'],
    image: {
      url: '',
      type: 'image',
      alt: 'BODA ALYSON-8917',
      orientation: 'landscape',
    },
    carouselMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: '1_7845',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '1_7854',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-1651',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-1770',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-8617',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-8917',
        orientation: 'landscape',
      },
    ],
    allMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: '1_7845',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '1_7854',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-1651',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-1770',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-8617',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-8917',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9010',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9063',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9081',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9094',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9509',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9523',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9568',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL 21743',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL 21830',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL 22003',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL 22033',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima578',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima581',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima610',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima626',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima629',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima634',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima664',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima669',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima680',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima726',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_1857',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_1883',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_1889',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_1991',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2077',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2090',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2262',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2344',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2363',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2600',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2616',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2833',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Civil Mili 2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Civil Mili 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Civil Mili 4',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Civil Mili 5',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Civil Mili 6',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Civil Mili',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 2 ',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 4',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 5',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 6',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 7',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_3615',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Pre Boda Omar-Fio2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Pre Boda Omar-Fio3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Pre Boda Omar-Fio5',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_8933',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_8967',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_9034',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_9060',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'bodas-12825',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'bodas-12849',
        orientation: 'portrait',
      },
    ],
  },
  {
    slug: 'fotos-productos',
    name: 'Fotografía de Productos',
    description:
      'Creamos imágenes de alta calidad que resaltan cada detalle, ayudando a que tu tienda online o catálogo destaque frente a la competencia.',
    portfolioDescription:
      'Cada producto tiene una historia. Nosotros la contamos con luz, enfoque y detalle.',
    points: [
      {
        title: 'Impacto visual inmediato',
        description:
          'Imágenes que destacan en catálogos y tiendas online, captando la atención de tu cliente ideal.',
      },
      {
        title: 'Listas para vender',
        description: 'Fotografía optimizada para e-commerce, redes sociales y campañas digitales.',
      },
      {
        title: 'Detalle que enamora',
        description: 'Resaltamos la textura, color y atributos únicos de cada producto.',
      },
    ],
    seoDescription:
      'Fotografía profesional de productos en Lima para e-commerce, catálogos y redes sociales. Imágenes que venden: fondo blanco, lifestyle y detalle. Cotiza gratis.',
    about: [
      'La fotografía de productos es la primera impresión que tu cliente recibe de tu marca. En una tienda online no puede tocar, oler ni probar lo que vendes: solo tiene la imagen. Por eso una foto profesional no es un lujo, es tu principal herramienta de ventas. En Visual Studio producimos fotografía de productos en Lima pensada para convertir visitas en compras, con la calidad que exigen plataformas como tu propia web, Mercado Libre, Shopify e Instagram.',
      'Trabajamos distintos estilos según lo que necesite cada producto. La toma en fondo blanco es ideal para catálogos y marketplaces (limpia, uniforme y sin distracciones). La fotografía lifestyle muestra el producto en uso y en contexto, ideal para redes sociales y campañas. Las tomas de detalle resaltan texturas, materiales y acabados, y las fotos de escala ayudan a que el cliente entienda el tamaño real. Definimos juntos la combinación que mejor comunica el valor de tu marca.',
      'Cada sesión incluye dirección de iluminación, composición y una edición cuidada (recorte, color fiel y limpieza de fondo) para que las imágenes lleguen listas para publicar. Entregamos los archivos en los formatos y proporciones que cada canal necesita, de modo que puedas cargarlos sin recortes ni pérdida de calidad. Si tienes un e-commerce, un catálogo o un lanzamiento en puerta, te ayudamos a que tus productos luzcan tan bien como merecen.',
    ],
    faqs: [
      {
        question: '¿Cuánto cuesta una sesión de fotografía de productos en Lima?',
        answer:
          'El precio depende de la cantidad de productos, el tipo de tomas (fondo blanco, lifestyle o detalle) y el nivel de edición que necesites. Armamos un paquete a la medida de tu marca. Escríbenos por WhatsApp y te enviamos una cotización gratuita sin compromiso.',
      },
      {
        question: '¿Cuántas fotos incluye la sesión?',
        answer:
          'La cantidad de imágenes finales se define según el paquete y el número de productos. En la cotización acordamos cuántas tomas por producto necesitas para tu catálogo, tienda online o redes, para que sepas exactamente qué vas a recibir.',
      },
      {
        question: '¿Necesito preparar mis productos antes de la sesión?',
        answer:
          'Sí. Recomendamos que los productos lleguen limpios, completos y en buen estado (sin polvo, huellas ni etiquetas provisionales). Si tu producto necesita montaje, styling o accesorios, coordinamos los detalles antes de la sesión para aprovechar el tiempo al máximo.',
      },
      {
        question: '¿Las fotos sirven para Mercado Libre, Shopify y redes sociales?',
        answer:
          'Sí. Entregamos las imágenes en los formatos y proporciones que cada plataforma requiere, de modo que puedas subirlas directamente a tu e-commerce, marketplace o redes sin recortes ni pérdida de calidad.',
      },
    ],
    image: {
      url: '',
      type: 'image',
      alt: 'Ynn Cafeteria',
      orientation: 'landscape',
    },
    carouselMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: '1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '5',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '6',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '7',
        orientation: 'portrait',
      },
    ],
    allMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: '1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '5',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '6',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '7',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '8',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'AKRON-PHRAMACEUTICA-11664',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'AKRON-PHRAMACEUTICA-11838',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'AKRON-PHRAMACEUTICA-12052',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'AKRON-PHRAMACEUTICA-12194',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Be Healthy Producto 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Be Healthy Producto 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Be Healthy Producto',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Biangel Producto 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Biangel Producto 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Biangel Producto',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CLAUDIA-ZSA-4938',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Descanso Ancestral',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'ENARMONIA-Producto 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ENARMONIA-Producto 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ENARMONIA-Producto-3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'HANA-H-2058',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'HANA-H-2262',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_0116',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_0118',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_0999',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-10011',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-10059',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9871',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9877',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9880',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9885',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9922',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9960',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9974',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ItsWood-Abril-15636',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ItsWood-Abril-15652',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ItsWood-Abril-15667',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ItsWood-Abril-15676',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ItsWood-Abril-15699',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ItsWood-Abril-15714',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Itswood Navidad',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LUKA CAJAS',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'LUKA-2401',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-3-5632',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-3-5641',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-3-5825',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Taller 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Taller 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Taller 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Tournasol Producto 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Tournasol Producto 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Tournasol Producto 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Ynn Cafeteria',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'feeling-biox-6106',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'feeling-biox-6143',
        orientation: 'portrait',
      },
    ],
  },
  {
    slug: 'fotos-moda',
    name: 'Fotografía de Moda',
    description:
      'Creamos sesiones de moda profesionales que destacan el estilo, la actitud y la personalidad de tu marca. Desde lookbooks hasta campañas publicitarias, capturamos imágenes que elevan el valor de tus prendas y conectan con tu público.',
    portfolioDescription:
      'Moda con identidad y fotografías que cuentan historias a través del estilo.',
    points: [
      {
        title: 'Imágenes que potencian tu marca',
        description:
          'Fotografías fashion con enfoque editorial, ideales para tiendas online, redes sociales y campañas.',
      },
      {
        title: 'Modelos, estilo y dirección creativa',
        description:
          'Guiamos cada pose, gesto y composición para resaltar las prendas y transmitir la esencia de tu colección.',
      },
      {
        title: 'Resultados listos para catálogos y e-commerce',
        description:
          'Entregamos contenido visual optimizado para plataformas digitales, lookbooks y publicidades.',
      },
    ],
    seoDescription:
      'Fotografía de moda en Lima para marcas, diseñadores y tiendas. Lookbooks, campañas y contenido editorial con dirección creativa. Estudio Visual Studio.',
    about: [
      'La fotografía de moda es la forma en que tu marca de ropa comunica quién es. No se trata solo de mostrar una prenda, sino de transmitir una actitud, un estilo y una historia que conecten con tu público. En Visual Studio producimos sesiones de fotografía de moda en Lima para marcas, diseñadores y tiendas que quieren que sus colecciones luzcan como merecen, con dirección creativa de principio a fin.',
      'Distinguimos entre la fotografía comercial y la editorial porque cada una cumple un objetivo distinto. La comercial prioriza la claridad de la prenda: colores fieles, calce y detalle, ideal para catálogos, lookbooks y e-commerce. La editorial construye un mundo alrededor de la colección (concepto, locación, estilismo y actitud), pensada para campañas, revistas y contenido de marca. En la cotización definimos cuál se ajusta mejor a lo que necesitas.',
      'Una buena sesión de moda se planifica: casting, selección de looks, locación, equipo de estilismo y una dirección clara de poses y luz. Nos encargamos de guiar cada detalle para que las prendas se vean bien y la imagen final tenga identidad. Entregamos el material editado y optimizado para el canal donde vas a publicarlo, ya sea tu tienda online, tus redes o una campaña. Si tienes una colección nueva o quieres renovar la imagen de tu marca, te ayudamos a contarla con fuerza.',
    ],
    faqs: [
      {
        question: '¿Cómo se cotiza una sesión de fotografía de moda?',
        answer:
          'La cotización depende del tipo de sesión (comercial o editorial), la cantidad de looks, la locación y el equipo necesario (modelo, estilismo, maquillaje). Conversamos tu proyecto, definimos el alcance y te enviamos una propuesta a medida. Escríbenos por WhatsApp para empezar.',
      },
      {
        question: '¿Incluyen modelo y maquilladora?',
        answer:
          'Podemos coordinar modelo, maquillaje y estilismo según las necesidades de tu proyecto. Algunas marcas traen su propio equipo y otras prefieren que nos encarguemos de todo. Lo definimos juntos en la cotización para armar la producción que mejor se ajuste a tu colección y presupuesto.',
      },
      {
        question: '¿Cuántos looks se pueden hacer en una sesión?',
        answer:
          'La cantidad de looks depende de la duración de la sesión y de la complejidad de cada cambio (prendas, maquillaje y locación). En la planificación previa acordamos cuántos looks entran para que aproveches al máximo el tiempo de producción.',
      },
    ],
    image: {
      url: '',
      type: 'image',
      alt: 'RUTH-281',
      orientation: 'landscape',
    },
    carouselMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: 'LIMA-SOFT-DIC-4289',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMA-SOFT-DIC-4296',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMA-SOFT-DIC-4310',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMA-SOFT-DIC-4317',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMA-SOFT-DIC-4336',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMA-SOFT-DIC-4350',
        orientation: 'portrait',
      },
    ],
    allMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: 'LIMA-SOFT-DIC-4289',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMA-SOFT-DIC-4296',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMA-SOFT-DIC-4310',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMA-SOFT-DIC-4317',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMA-SOFT-DIC-4336',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMA-SOFT-DIC-4350',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'XOMFY-VERANO-3122',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'XOMFY-VERANO-3183',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'XOMFY-VERANO-3239',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'XOMFY-VERANO-3331',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'XOMFY-VERANO-3418',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '1 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '101---Bilancia-Verano-2024-2511',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '326---Bilancia-Verano-2024-2797',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '6',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'ALMAT-5119',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ALMAT-5203',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BOHO 4-7176',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BOHO 4-7199',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COMFY66-5177',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COMFY66-5211',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COMFY66-5277',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COMFY66-5506',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COMFY66-5555',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Carteras-angie-17913',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Carteras-angie-17961',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Carteras-angie-17967',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Carteras-angie-18046',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Comfy-Dic-2-6904',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Comfy-Dic-2-7000',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ISABEL FLORES ',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ISABEL FLORES-6284',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ISABEL FLORES-6296',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ISABEL-FLORES-3-7583',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ISABEL-FLORES-3-7977',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMAsoft-2785',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMAsoft-2792',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMAsoft-2813',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16291',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16326',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16368',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16375',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16389',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16394',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16409',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'MAITENE-17526',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21358',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21373',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21392',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21416',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21441',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21456',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21485',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21517',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA-VIERNES-22124',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA-VIERNES-22125',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA-VIERNES-22164',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA-VIERNES-22250',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-242',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-246',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-273',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-281',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-417',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'belle-oct-2008',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'belle-oct-2025',
        orientation: 'portrait',
      },
    ],
  },
  {
    slug: 'fotos-corporativas',
    name: 'Eventos Corporativos',
    description:
      'Mostramos la personalidad y los valores de tu empresa en cada retrato, generando confianza en clientes, socios y colaboradores.',
    portfolioDescription: 'La imagen de tu empresa, en su mejor versión.',
    points: [
      {
        title: 'Proyecta profesionalismo',
        description: 'Retratos corporativos y de equipo que transmiten confianza.',
      },
      {
        title: 'Marca con identidad',
        description: 'Fotografías de espacios y procesos que cuentan la historia de tu negocio.',
      },
      {
        title: 'Visibilidad en todos los canales',
        description: 'Imágenes ideales para web, presentaciones y redes sociales.',
      },
    ],
    seoDescription:
      'Fotografía de eventos corporativos y retratos empresariales en Lima. Conferencias, lanzamientos y fotos de equipo que proyectan profesionalismo. Visual Studio.',
    about: [
      'La imagen de tu empresa comunica confianza antes de que digas una palabra. Nuestro servicio de fotografía corporativa y de eventos en Lima ayuda a marcas y empresas a proyectar profesionalismo en cada canal: tu web, tus perfiles de LinkedIn, tus presentaciones comerciales y tus notas de prensa. Capturamos la personalidad y los valores de tu organización con un enfoque cuidado y consistente con tu identidad de marca.',
      'Cubrimos conferencias, congresos, lanzamientos de producto, capacitaciones, aniversarios y eventos de empresa, documentando tanto los momentos clave como la interacción entre los asistentes. También realizamos retratos corporativos y fotos de equipo (headshots) uniformes para toda la plantilla, ideales para directorios, perfiles profesionales y material institucional. Trabajamos con discreción para no interrumpir el desarrollo de tu evento.',
      'Entendemos que muchos eventos corporativos necesitan material rápido para publicar en redes o enviar a prensa. Por eso coordinamos tiempos de entrega ágiles y adaptamos los formatos a cada uso. Atendemos eventos en Lima y sus distritos. Cuéntanos la fecha, el lugar y el objetivo de tu evento y armamos una cobertura a la medida de tu empresa.',
    ],
    faqs: [
      {
        question: '¿Qué tipo de eventos corporativos cubren?',
        answer:
          'Cubrimos conferencias, congresos, lanzamientos de producto, capacitaciones, aniversarios, cenas de empresa y activaciones de marca, además de retratos corporativos y fotos de equipo. Si tienes un formato distinto, cuéntanos y evaluamos cómo cubrirlo.',
      },
      {
        question: '¿Ofrecen retratos de equipo y headshots profesionales?',
        answer:
          'Sí. Realizamos sesiones de retratos corporativos con un estilo uniforme para todo el equipo, ideales para perfiles de LinkedIn, la web de la empresa y material institucional. Podemos hacerlos en tu oficina o en la locación que definamos.',
      },
      {
        question: '¿Pueden cubrir eventos en cualquier distrito de Lima?',
        answer:
          'Sí, atendemos eventos corporativos en Lima y sus distritos. Coordinamos con anticipación la logística, los horarios y los puntos clave a cubrir para asegurar una cobertura completa el día del evento.',
      },
    ],
    videos: ['5ZC-84NjceA', '7swe52Y9SU0', 'lV0CH0JtnXA', 'x6BQ68IowkA'],
    image: {
      url: '',
      type: 'image',
      alt: 'CELELPSA 3561',
      orientation: 'landscape',
    },
    carouselMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: 'AICI 1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'AICI 2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'AICI 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'ALPHA 1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'ALPHA 2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'ALPHA 3',
        orientation: 'portrait',
      },
    ],
    allMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: 'AICI 1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'AICI 2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'AICI 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'ALPHA 1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'ALPHA 2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'ALPHA 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'AZZORTI 1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'AZZORTI 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'AZZORTI 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'COLEGIO MEDICO 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COLEGIO MEDICO 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COLEGIO MEDICO 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'COLEGIO MEDICO 4',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'COURTYARD 1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'COURTYARD 2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'COURTYARD 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'DISPOLAB 1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'DISPOLAB 2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'DISPOLAB 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'DISPOLAB 4',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'DISPOLAB 5',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'MICROTECH 1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'MICROTECH 2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'MICROTECH 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'MICROTECH 4',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'MICROTECH 5',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3561',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3570',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3695',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3754',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3842',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3963',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3991',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4084',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4113',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4181',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4205',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4247',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4258',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4530',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CENERGIA-18245',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CENERGIA-18269',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COURTYARD5366',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'COURTYARD5419',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'COURTYARD5545',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'COURTYARD5558',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo 5',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo 9',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_0541',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_0751',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_9517',
        orientation: 'landscape',
      },
    ],
  },
  {
    slug: 'fotos-familia',
    name: 'Fotografía Familiar',
    description:
      'Sesiones fotográficas naturales y llenas de vida para familias, parejas, niños, embarazadas y quienes desean conservar recuerdos auténticos. Capturamos momentos reales, espontáneos y emotivos que reflejan tu historia.',
    portfolioDescription:
      'Instantes genuinos que hablan de ti, de tu familia y de los momentos que atesoras.',
    points: [
      {
        title: 'Momentos que importan',
        description:
          'Fotografías espontáneas y naturales que capturan la esencia de tu familia, pareja o celebración personal.',
      },
      {
        title: 'Sesiones para cada etapa',
        description:
          'Maternidad, bebés, niños, cumpleaños, mascotas o retratos personales: documentamos lo que hace única tu historia.',
      },
      {
        title: 'Recuerdos llenos de emoción',
        description:
          'Imágenes cálidas y cuidadas, ideales para álbumes, impresiones o compartir en tus redes sociales.',
      },
    ],
    seoDescription:
      'Sesiones de fotografía familiar en Lima: familias, parejas, niños, embarazo y bebés. Recuerdos naturales y emotivos. Reserva tu sesión con Visual Studio.',
    about: [
      'Las fotos familiares son de esas cosas que agradeces años después. Nuestras sesiones de fotografía familiar en Lima capturan momentos reales, espontáneos y llenos de emoción: el juego con tus hijos, la complicidad en pareja, la espera de un bebé o una celebración importante. Buscamos que cada imagen refleje quiénes son ustedes, con un estilo natural y cálido, lejos de las poses rígidas de estudio tradicional.',
      'Acompañamos cada etapa de la historia familiar. Realizamos sesiones de embarazo (maternidad), recién nacidos y bebés, niños, cumpleaños, bautizos, sesiones de pareja y retratos personales. También documentamos a las mascotas, que muchas veces son parte esencial de la familia. Adaptamos el ritmo de la sesión a la edad y comodidad de los más pequeños, para que todos disfruten el proceso y las fotos salgan genuinas.',
      'Las sesiones se realizan en la locación que elijas: exteriores, tu hogar o el lugar que tenga un significado especial para ustedes (lo coordinamos al reservar). Entregamos imágenes editadas con cuidado, ideales para álbumes, impresiones o compartir en redes. Escríbenos y armamos juntos una sesión pensada para tu familia.',
    ],
    faqs: [
      {
        question: '¿Cuánto dura una sesión de fotografía familiar?',
        answer:
          'La duración varía según el tipo de sesión y la cantidad de personas, pero la mayoría de sesiones familiares dura entre una y dos horas. Cuando hay niños pequeños o bebés, manejamos los tiempos con flexibilidad para respetar sus ritmos y lograr fotos naturales.',
      },
      {
        question: '¿Dónde se realizan las sesiones?',
        answer:
          'Realizamos las sesiones en la locación que prefieras: exteriores (parques, playa, lugares al aire libre), tu propia casa o un sitio con valor sentimental para tu familia. Definimos el lugar juntos al momento de reservar según el estilo que buscas.',
      },
      {
        question: '¿Qué tipos de sesiones familiares ofrecen?',
        answer:
          'Ofrecemos sesiones de embarazo, recién nacidos y bebés, niños, cumpleaños, bautizos, parejas, retratos personales y sesiones con mascotas. Si tienes una idea o una ocasión especial en mente, cuéntanos y la adaptamos a tu historia.',
      },
    ],
    image: {
      url: '',
      type: 'image',
      alt: 'Cumple Leah999_494',
      orientation: 'landscape',
    },
    carouselMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: 'BAUTIZO 1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BAUTIZO 2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BAUTIZO 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CORPANCHO-5243',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CORPANCHO-5248',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CORPANCHO-5255',
        orientation: 'landscape',
      },
    ],
    allMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: 'BAUTIZO 1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BAUTIZO 2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BAUTIZO 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CORPANCHO-5243',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CORPANCHO-5248',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CORPANCHO-5255',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CUMPLE MASSI 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CUMPLE MASSI 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CUMPLE MASSI 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'EMBARAZO-1962',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'EMBARAZO-2050',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'EMBARAZO-2060',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'MARIA-VICTORIA-FAM-8725-v2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'MARIA-VICTORIA-FAM-8725',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'MARIA-VICTORIA-FAM-8847',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'MELLIS 1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'MELLIS 2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'MELLIS 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'PRIMER AÑO 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'PRIMER AÑO 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'PRIMER AÑO 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'SUSANNE-4540',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'SUSANNE-4582',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'SUSANNE-4693',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'embarazo-24691',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'embarazo-24753',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'embarazo-24851',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-15794',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-15798',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-15840',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-15943',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-16044',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CUMPLE-OLIVIA_4985',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CUMPLE-OLIVIA_5006',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CUMPLE-OLIVIA_5525',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CUMPLE-OLIVIA_6006',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Cumple Leah763',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Cumple Leah931',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Cumple Leah968',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Cumple Leah999_29',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Cumple Leah999_494',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Cumple Leah999_8',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia (1)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia (2)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia (3)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia (4)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 4',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 5',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 6',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 7',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Paz 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Paz 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Paz 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Paz 6',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_8805',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_8883',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_8898',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_9087',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_9209',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_9291',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'MARIA-VICTORIA-FAM-8725',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (1)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (2)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (3)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (4)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (5)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (6)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (7)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (8)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_5543',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_5774',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_5844',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_5864',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_5915',
        orientation: 'portrait',
      },
    ],
  },
  // {
  //   slug: 'podcast',
  //   name: 'Podcast',
  //   description:
  //     'Nos encargamos de la grabación, montaje y postproducción de tu podcast para que suene impecable y conecte con tu audiencia.',
  //   portfolioDescription: 'Tu voz puede llegar más lejos. Nosotros te ayudamos a amplificarla.',
  //   points: [
  //     {
  //       title: 'Proyecta profesionalismo',
  //       description: 'Grabación y edición de audio con calidad de estudio.',
  //     },
  //     {
  //       title: 'Marca con identidad',
  //       description: 'Desde la preparación hasta el montaje final, nos encargamos de todo.',
  //     },
  //     {
  //       title: 'Visibilidad en todos los canales',
  //       description: 'Podcasts diseñados para conectar con tu audiencia y fortalecer tu marca.',
  //     },
  //   ],
  //   image: {
  //     url: '',
  //     type: 'image',
  //     alt: 'Podcast',
  //   },
  //   carouselMediaFiles: [],
  //   allMediaFiles: [],
  // },
]);
