import type { MediaFile } from '@/types/mediaFile';
import type { Service } from '@/types/service';

const MEDIA_URL = import.meta.env.MEDIA_URL;

const addCarouselImages = (services: Service[]) => {
  return services.map((service) => {
    return {
      ...service,
      image: {
        ...service.image,
        url: `${MEDIA_URL}/services/${service.slug}/${service.image.alt}`,
      } as MediaFile,
      allMediaFiles: service.allMediaFiles.map((mediaFile) => {
        return {
          ...mediaFile,
          url:
            mediaFile.type === 'video'
              ? mediaFile.url
              : `${MEDIA_URL}/services/${service.slug}/${mediaFile.alt}`,
        };
      }) as MediaFile[],
      carouselMediaFiles: service.carouselMediaFiles.map((mediaFile) => {
        return {
          ...mediaFile,
          url: `${MEDIA_URL}/services/${service.slug}/${mediaFile.alt}`,
        };
      }) as MediaFile[],
    };
  });
};

export const SERVICES: Service[] = addCarouselImages([
  {
    slug: 'fotos-bodas',
    name: 'Fotografía de bodas',
    description:
      'Capturamos cada emoción de tu boda con un estilo natural, elegante y atemporal. Nuestro servicio de fotografía de bodas inmortaliza los momentos más importantes de tu gran día para que puedas revivirlos por siempre.',
    portfolioDescription:
      'Tu historia de amor contada en imágenes reales, emotivas y llenas de vida.',
    points: [
      {
        title: 'Momentos reales, sin poses forzadas',
        description:
          'Capturamos cada risa, lágrima y abrazo de forma natural, para que tus fotos reflejen exactamente lo que viviste.',
      },
      {
        title: 'Cobertura completa de tu gran día',
        description:
          'Desde los preparativos hasta la fiesta, documentamos cada etapa de tu boda con un enfoque artístico y profesional.',
      },
      {
        title: 'Recuerdos que duran para siempre',
        description:
          'Entregamos fotografías de alta calidad, ideales para álbumes, redes sociales e impresiones de gran formato.',
      },
    ],
    image: {
      url: '',
      type: 'image',
      alt: 'BODA ALYSON-8917',
      orientation: 'landscape',
    },
    carouselMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: '1_7845',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '1_7854',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-1651',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-1770',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-8617',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-8917',
        orientation: 'landscape',
      },
    ],
    allMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: '1_7845',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '1_7854',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-1651',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-1770',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-8617',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-8917',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9010',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9063',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9081',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9094',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9509',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9523',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA ALYSON-9568',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL 21743',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL 21830',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL 22003',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL 22033',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima578',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima581',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima610',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima626',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima629',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima634',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima664',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima669',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima680',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA CIVIL-Lima726',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_1857',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_1883',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_1889',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_1991',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2077',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2090',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2262',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2344',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2363',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2600',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2616',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'BODA OMAR - FIORELA_2833',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Civil Mili 2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Civil Mili 3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Civil Mili 4',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Civil Mili 5',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Civil Mili 6',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Civil Mili',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 2 ',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 4',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 5',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 6',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Boda Religiosa Mili 7',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_3615',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Pre Boda Omar-Fio2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Pre Boda Omar-Fio3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Pre Boda Omar-Fio5',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_8933',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_8967',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_9034',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_9060',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'bodas-12825',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'bodas-12849',
        orientation: 'portrait',
      },
    ],
  },
  {
    slug: 'fotos-productos',
    name: 'Fotografía de productos',
    description:
      'Creamos imágenes de alta calidad que resaltan cada detalle, ayudando a que tu tienda online o catálogo destaque frente a la competencia.',
    portfolioDescription:
      'Cada producto tiene una historia. Nosotros la contamos con luz, enfoque y detalle.',
    points: [
      {
        title: 'Impacto visual inmediato',
        description:
          'Imágenes que destacan en catálogos y tiendas online, captando la atención de tu cliente ideal.',
      },
      {
        title: 'Listas para vender',
        description: 'Fotografía optimizada para e-commerce, redes sociales y campañas digitales.',
      },
      {
        title: 'Detalle que enamora',
        description: 'Resaltamos la textura, color y atributos únicos de cada producto.',
      },
    ],
    image: {
      url: '',
      type: 'image',
      alt: 'Ynn Cafeteria',
      orientation: 'landscape',
    },
    carouselMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: '1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '5',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '6',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '7',
        orientation: 'portrait',
      },
    ],
    allMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: '1',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '2',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '3',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '5',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '6',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '7',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '8',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'AKRON-PHRAMACEUTICA-11664',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'AKRON-PHRAMACEUTICA-11838',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'AKRON-PHRAMACEUTICA-12052',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'AKRON-PHRAMACEUTICA-12194',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Be Healthy Producto 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Be Healthy Producto 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Be Healthy Producto',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Biangel Producto 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Biangel Producto 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Biangel Producto',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CLAUDIA-ZSA-4938',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Descanso Ancestral',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'ENARMONIA-Producto 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ENARMONIA-Producto 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ENARMONIA-Producto-3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'HANA-H-2058',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'HANA-H-2262',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_0116',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_0118',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_0999',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-10011',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-10059',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9871',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9877',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9880',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9885',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9922',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9960',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ITS-WOOD-ENERO-25-9974',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ItsWood-Abril-15636',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ItsWood-Abril-15652',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ItsWood-Abril-15667',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ItsWood-Abril-15676',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ItsWood-Abril-15699',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ItsWood-Abril-15714',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Itswood Navidad',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LUKA CAJAS',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'LUKA-2401',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-3-5632',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-3-5641',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-3-5825',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Taller 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Taller 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Taller 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Tournasol Producto 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Tournasol Producto 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Tournasol Producto 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Ynn Cafeteria',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'feeling-biox-6106',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'feeling-biox-6143',
        orientation: 'portrait',
      },
    ],
  },
  {
    slug: 'fotos-moda',
    name: 'Fotografía de moda',
    description:
      'Creamos sesiones de moda profesionales que destacan el estilo, la actitud y la personalidad de tu marca. Desde lookbooks hasta campañas publicitarias, capturamos imágenes que elevan el valor de tus prendas y conectan con tu público.',
    portfolioDescription:
      'Moda con identidad y fotografías que cuentan historias a través del estilo.',
    points: [
      {
        title: 'Imágenes que potencian tu marca',
        description:
          'Fotografías fashion con enfoque editorial, ideales para tiendas online, redes sociales y campañas.',
      },
      {
        title: 'Modelos, estilo y dirección creativa',
        description:
          'Guiamos cada pose, gesto y composición para resaltar las prendas y transmitir la esencia de tu colección.',
      },
      {
        title: 'Resultados listos para catálogos y e-commerce',
        description:
          'Entregamos contenido visual optimizado para plataformas digitales, lookbooks y publicidades.',
      },
    ],
    image: {
      url: '',
      type: 'image',
      alt: 'RUTH-281',
      orientation: 'landscape',
    },
    carouselMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: '1 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '101---Bilancia-Verano-2024-2511',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '326---Bilancia-Verano-2024-2797',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '6',
        orientation: 'landscape',
      },
    ],
    allMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: '1 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '101---Bilancia-Verano-2024-2511',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '326---Bilancia-Verano-2024-2797',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '6',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'ALMAT-5119',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ALMAT-5203',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BOHO 4-7176',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'BOHO 4-7199',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COMFY66-5177',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COMFY66-5211',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COMFY66-5277',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COMFY66-5506',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COMFY66-5555',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Carteras-angie-17913',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Carteras-angie-17961',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Carteras-angie-17967',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Carteras-angie-18046',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Comfy-Dic-2-6904',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Comfy-Dic-2-7000',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ISABEL FLORES ',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ISABEL FLORES-6284',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ISABEL FLORES-6296',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ISABEL-FLORES-3-7583',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ISABEL-FLORES-3-7977',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMAsoft-2785',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMAsoft-2792',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'LIMAsoft-2813',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16291',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16326',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16368',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16375',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16389',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16394',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Lima-soft-16409',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'MAITENE-17526',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21358',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21373',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21392',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21416',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21441',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21456',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21485',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA VIERNES-21517',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA-VIERNES-22124',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA-VIERNES-22125',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA-VIERNES-22164',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'ROPA-VIERNES-22250',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-242',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-246',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-273',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-281',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'RUTH-417',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'belle-oct-2008',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'belle-oct-2025',
        orientation: 'portrait',
      },
    ],
  },
  {
    slug: 'fotos-corporativas',
    name: 'Fotografía de empresas',
    description:
      'Mostramos la personalidad y los valores de tu empresa en cada retrato, generando confianza en clientes, socios y colaboradores.',
    portfolioDescription: 'La imagen de tu empresa, en su mejor versión.',
    points: [
      {
        title: 'Proyecta profesionalismo',
        description: 'Retratos corporativos y de equipo que transmiten confianza.',
      },
      {
        title: 'Marca con identidad',
        description: 'Fotografías de espacios y procesos que cuentan la historia de tu negocio.',
      },
      {
        title: 'Visibilidad en todos los canales',
        description: 'Imágenes ideales para web, presentaciones y redes sociales.',
      },
    ],
    image: {
      url: '',
      type: 'image',
      alt: 'CELELPSA 3561',
      orientation: 'landscape',
    },
    carouselMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: 'CAROLINA COLOR-10719',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CAROLINA-COLOR-10590',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CAROLINA-COLOR-10615',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CAROLINA-COLOR-10620',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3561',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3570',
        orientation: 'landscape',
      },
    ],
    allMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: 'CAROLINA COLOR-10719',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CAROLINA-COLOR-10590',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CAROLINA-COLOR-10615',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CAROLINA-COLOR-10620',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3561',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3570',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3596',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3695',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3754',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3842',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3963',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 3991',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4084',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4113',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4181',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4205',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4247',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4258',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4367',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4437',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4450',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4487',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4499',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4525',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CELELPSA 4530',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CENERGIA-18245',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CENERGIA-18269',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CIELO-18523',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CIELO-18751',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'COURTYARD5366',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'COURTYARD5419',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'COURTYARD5545',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'COURTYARD5558',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'KATI-GALINDO-TEAM-13325',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'KATI-GALINDO-TEAM-13455',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'KATI-GALINDO-TEAM-13476',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'KATI-GALINDO-TEAM-13482',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'KATI-GALINDO-TEAM-13486',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'KATI-GALINDO-TEAM-13487',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'KATI-GALINDO-TEAM-13495',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo 5',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo 9',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_0541',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_0751',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_9517',
        orientation: 'landscape',
      },
    ],
  },
  {
    slug: 'fotos-familia',
    name: 'Fotografía familiar',
    description:
      'Sesiones fotográficas naturales y llenas de vida para familias, parejas, niños, embarazadas y quienes desean conservar recuerdos auténticos. Capturamos momentos reales, espontáneos y emotivos que reflejan tu historia.',
    portfolioDescription:
      'Instantes genuinos que hablan de ti, de tu familia y de los momentos que atesoras.',
    points: [
      {
        title: 'Momentos que importan',
        description:
          'Fotografías espontáneas y naturales que capturan la esencia de tu familia, pareja o celebración personal.',
      },
      {
        title: 'Sesiones para cada etapa',
        description:
          'Maternidad, bebés, niños, cumpleaños, mascotas o retratos personales: documentamos lo que hace única tu historia.',
      },
      {
        title: 'Recuerdos llenos de emoción',
        description:
          'Imágenes cálidas y cuidadas, ideales para álbumes, impresiones o compartir en tus redes sociales.',
      },
    ],
    image: {
      url: '',
      type: 'image',
      alt: 'Cumple Leah999_494',
      orientation: 'landscape',
    },
    carouselMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-15794',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-15798',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-15840',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-15943',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-16044',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CUMPLE-OLIVIA_4985',
        orientation: 'landscape',
      },
    ],
    allMediaFiles: [
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-15794',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-15798',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-15840',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-15943',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CATHERINE-EMBARAZO-16044',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'CUMPLE-OLIVIA_4985',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CUMPLE-OLIVIA_5006',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CUMPLE-OLIVIA_5525',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'CUMPLE-OLIVIA_6006',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Cumple Leah763',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Cumple Leah931',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Cumple Leah968',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Cumple Leah999_29',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Cumple Leah999_494',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Cumple Leah999_8',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia (1)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia (2)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia (3)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia (4)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 4',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 5',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 6',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Liza 7',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Paz 1',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Paz 2',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Paz 3',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Familia Paz 6',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_8805',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_8883',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_8898',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_9087',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_9209',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'IMG_9291',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'MARIA-VICTORIA-FAM-8725',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (1)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (2)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (3)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (4)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (5)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (6)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (7)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: 'Mesa de trabajo (8)',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_5543',
        orientation: 'landscape',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_5774',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_5844',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_5864',
        orientation: 'portrait',
      },
      {
        url: '',
        type: 'image',
        alt: '_MG_5915',
        orientation: 'portrait',
      },
    ],
  },
  // {
  //   slug: 'podcast',
  //   name: 'Podcast',
  //   description:
  //     'Nos encargamos de la grabación, montaje y postproducción de tu podcast para que suene impecable y conecte con tu audiencia.',
  //   portfolioDescription: 'Tu voz puede llegar más lejos. Nosotros te ayudamos a amplificarla.',
  //   points: [
  //     {
  //       title: 'Proyecta profesionalismo',
  //       description: 'Grabación y edición de audio con calidad de estudio.',
  //     },
  //     {
  //       title: 'Marca con identidad',
  //       description: 'Desde la preparación hasta el montaje final, nos encargamos de todo.',
  //     },
  //     {
  //       title: 'Visibilidad en todos los canales',
  //       description: 'Podcasts diseñados para conectar con tu audiencia y fortalecer tu marca.',
  //     },
  //   ],
  //   image: {
  //     url: '',
  //     type: 'image',
  //     alt: 'Podcast',
  //   },
  //   carouselMediaFiles: [],
  //   allMediaFiles: [],
  // },
]);
